function newStation() {
  var randomStation = Math.floor(Math.random() * stations.length());
  document.getElementById('stationDisplay').innerHTML = stations[randomStation];
}

var stations = [
  'NS1|EW24|JE5 - Jurong East'
  'NS2 - Bukit Batok'
  'NS3 - Bukit Gambok'
  'NS4|JS1|BP1 - Choa Chu Kang'
  'NS5 - Yew Tee'
  'NS7 - Kranji'
  'NS8 - Marsiling'
  'NS9 - Woodlands'
  'NS10 - Admiralty'
  'NS11 - Sembawang'
  'NS12 - Canberra'
  'NS13 - Yishun'
  'NS14 - Khatib'
  'NS15 - Yio Chu Kang'
  'NS16 - Ang Mo Kio'
  'NS17|CC15 - Bishan'
  'NS18 - Braddell'
  'NS19 - Toa Payoh'
  'NS20 - Novena'
  'NS21|DT11 - Newton'
  'NS22 - Orchard'
  'NS23 - Somerset'
  'NS24|NE6|CC1 - Dhoby Ghaut'
  'NS25|EW13 - City Hall'
  'NS26|EW14 - Raffles Place'
  'NS27|CE2 - Marina Bay'
  'NS28 - Marina South Pier'
  'EW1 - Pasir Ris'
  'EW2|DT32 - Tampines'
  'EW3 - Simei'
  'EW4 - Tanah Merah'
  'EW5 - Bedok'
  'EW6 - Kembangan'
  'EW7 - Eunos'
  'EW8|CC9 - Paya Lebar'
  'EW9 - Aljunied'
  'EW10 - Kallang'
  'EW11 - Lavender'
  'EW12|DT14 - Bugis'
  'EW15 - Tanjong Pagar'
  'EW16|NE3 - Outram Park'
  'EW17 - Tiong Bahru'
  'EW18 - Redhill'
  'EW19 - Queenstown'
  'EW20 - Commonwealth'
  'EW21|CC22 - Buona Vista'
  'EW22 - Dover'
  'EW23 - Clementi'
  'EW25 - Chinese Garden'
  'EW26 - Lakeside'
  'EW27 - Boon Lay'
  'EW28 - Pioneer'
  'EW29 - Joo Koon'
  'EW30 - Gul Circle'
  'EW31 - Tuas Crescent'
  'EW32 - Tuas West Road'
  'EW33 - Tuas Link'
  'CG1 - Expo'
  'CG2 - Changi Airport'
  'NE1|CC29 - Harbour Front'
  'NE4|DT19 - Chinatown'
  'NE5 - Clarke Quay'
  'NE7|DT12 - Little India'
  'NE8 - Farrer Park'
  'NE9 - Boon Keng'
  'NE10 - Potong Pasir'
  'NE11 - Woodleigh'
  'NE12|CC13 - Serangoon'
  'NE13 - Kovan'
  'NE14 - Hougang'
  'NE15 - Buangkok'
  'NE16|STC - Sengkang'
  'NE17|PTC - Punggol'
]
