function newStation() {
  var randomStation = Math.floor(Math.random() * stations.length);
  document.getElementById('stationDisplay').innerHTML = stations[randomStation];
}

var stations = [
  'Jurong East (NS1/EW24/JE5)',
  'Bukit Batok (NS2)',
  'Bukit Gambok (NS3)',
  'Choa Chu Kang (NS4/JS1/BP1)',
  'Yew Tee (NS5)',
  'Kranji (NS7)',
  'Marsiling (NS8)',
  'Woodlands (NS9)',
  'Admiralty (NS9)',
  'Sembawang (NS11)',
  'Canberra (NS12)',
  'Yishun (NS13)',
  'Khatib (NS14)',
  'Yio Chu Kang (NS15)',
  'Ang Mo Kio (NS16)',
  'Bishan (NS17/CC15)',
  'Braddell (NS18)',
  'Toa Payoh (NS19)',
  'Novena (NS20)',
  'Newton (NS21/DT11)',
  'Orchard (NS22)',
  'Somerset (NS23)',
  'Dhoby Ghaut (NS24/NE6/CC1)',
  'City Hall (NS25/EW13)',
  'Raffles Place (NS26/EW14)',
  'Marina Bay (NS27/CE2)',
  'Marina South Pier (NS28)',
  'Pasir Ris (EW1)',
  'Tampines (EW2/DT32)',
  'Simei (EW3)',
  'Tanah Merah (EW4)',
  'Bedok (EW5)',
  'Kembangan (EW6)',
  'Eunos (EW7)',
  'Paya Lebar (EW8/CC9)',
  'Aljunied (EW9)',
  'Kallang (EW10)',
  'Lavender (EW11)',
  'Bugis (EW12/DT14)',
  'Tanjong Pagar (EW15)',
  'Outram Park (EW16/NE3)',
  'Tiong Bahru (EW17)',
  'Redhill (EW18)',
  'Queenstown (EW19)',
  'Commonwealth (EW20)',
  'Buona Vista (EW21/CC22)',
  'Dover (EW22)',
  'Clementi (EW23)',
  'Chinese Garden (EW25)',
  'Lakeside (EW26)',
  'Boon Lay (EW27)',
  'Pioneer (EW28)',
  'Joo Koon (EW29)',
  'Gul Circle (EW30)',
  'Tuas Crescent (EW31)',
  'Tuas West Road (EW32)',
  'Tuas Link (EW33)',
  'Expo (CG1)',
  'Changi Airport (CG2)',
  'Harbour Front (NE1/CC29)',
  'Chinatown (NE4/DT19)',
  'Clarke Quay (NE5)',
  'Little India (NE7/DT12)',
  'Farrer Park (NE8)',
  'Boon Keng (NE9)',
  'Potong Pasir (NE10)',
  'Woodleigh (NE11)',
  'Serangoon (NE12/CC13)',
  'Kovan (NE13)',
  'Hougang (NE14)',
  'Buangkok (NE15)',
  'Sengkang (NE16/STC)',
  'Punggol(NE17/PTC)'
]
